chooseCRANmirror(ind = 77)
install.packages("stringr")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("tidyr")
install.packages("tidyverse")
install.packages("ggrepel")
install.packages("cowplot")
install.packages("ggpp")
install.packages("tm")
install.packages("SnowballC")
install.packages("wordcloud")
install.packages("RColorBrewer")
install.packages("syuzhet")
