chooseCRANmirror(ind = 77)
install.packages("stringr")
print("stringr installed.")
install.packages("dplyr")
print("dplyr installed.")
install.packages("ggplot2")
print("ggplot2 installed.")
install.packages("tidyr")
print("tidyr installed.")
install.packages("tidyverse")
print("tidyverse installed.")
install.packages("ggrepel")
print("ggrepel installed.")
install.packages("cowplot")
print("cowplot installed.")
install.packages("ggpp")
print("ggpp installed.")